fagongzi/goetty

application.go
application_test.go
buf/buf.go
session.go

Fixes #9 
Not Available
Not Available
Not Available

Fix data race

---

application_test.go
session.go

Fixes #
Not Available
Not Available
Not Available

Fix channel block

---

application.go
application_test.go
go.mod
go.sum
session.go
vendor/github.com/valyala/tcplisten/.travis.yml
vendor/github.com/valyala/tcplisten/LICENSE
vendor/github.com/valyala/tcplisten/README.md
vendor/github.com/valyala/tcplisten/go.mod
vendor/github.com/valyala/tcplisten/socket.go
vendor/github.com/valyala/tcplisten/socket_darwin.go
vendor/github.com/valyala/tcplisten/socket_other.go
vendor/github.com/valyala/tcplisten/tcplisten.go
vendor/github.com/valyala/tcplisten/tcplisten_bsd.go
vendor/github.com/valyala/tcplisten/tcplisten_linux.go
vendor/modules.txt

Fixes #
Not Available
Not Available
Not Available

Support SO_REUSEPORT

---

application.go
application_test.go

Fixes #13 
Not Available
Not Available
Not Available

Fix #13 read not return

---

session.go

Fixes #
Not Available
Not Available
Not Available

export tcp conn

---

application.go
go.mod
go.sum
net_darwin.go
net_linux.go
net_windows.go

Fixes #19
remove github.com/valyala/tcplisten dependence.
Not Available
Not Available

set SO_REUSEPORT and TCP_FASTOPEN with net.ListenConfig.Control

---

application.go
application_test.go
example/echo_server.go
session.go
session_test.go

Fixes #
Not Available
Not Available
Not Available

Support unix socket

---

application.go
session.go
session_test.go

Fixes #
Not Available
Not Available
Not Available

Add timeout read/write to IOSession

---

application.go

Fixes #
Not Available
Not Available
Not Available

fix mem alloc

---

option.go
session.go

Fixes #
Not Available
Not Available
Not Available

Add disable release out buf option

---

option.go
session.go

Fixes #
Not Available
Not Available
Not Available

Add buf pool option for iosession

---

application.go
proxy.go
proxy_test.go
session.go

Fixes #
Not Available
Not Available
Not Available

Add simple proxy

---

application.go

Fixes #
Not Available
Not Available
Not Available

fix close data race

---

session.go
session_test.go

Fixes #
Not Available
Not Available
Not Available

Add set net.conn for IOSession

---

buf/buf.go
session.go

Fixes #
Not Available
Not Available
Not Available

Add some method to compatible v1

---

session.go

Fixes #
Not Available
Not Available
Not Available

Add options to disable auto reset read buffer

---

session.go

Fixes #
Not Available
Not Available
Not Available

fix logger level

---

session.go
session_test.go

Fixes #
Not Available
Not Available
Not Available

deincr ref count after state check

---

application.go
application_test.go
proxy_test.go
session_test.go

Fixes #
Not Available
Not Available
Not Available

add multi listener support

---

buf/buf.go
buf/buf_test.go
codec/length/codec_length_field.go
session.go

Fixes #
Not Available
Not Available
Not Available

add disable reset read and write after buf gow

---

buf/buf.go

Fixes #
Not Available
Not Available
Not Available

add new writeIndex methods

---

buf/buf.go

Fixes #
Not Available
Not Available
Not Available

fix set write index by offset

---

session.go

Fixes #
Not Available
Not Available
Not Available

fix concurrent close not work

---

session.go

Fixes #
Not Available
Not Available
Not Available

fix close not disconnect connection

---

codec/length/codec_length_field.go
codec/length/codec_length_field_test.go

Fixes #
Not Available
Not Available
Not Available

return error if received a zero length packet

---

codec/length/codec_length_field.go
codec/length/codec_length_field_test.go

Fixes #
Not Available
Not Available
Not Available

Return error insteadof panic

---

buffered.go
session.go

Fixes #
Not Available
Not Available
Not Available

adjust interface
